name: ssrs_env
channels:
  - conda-forge
dependencies:
  - python >=3.8
  - matplotlib>=3.4
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - pathos>=0.2
  - rasterio>=1.2
  - elevation>=1.1
  - h5py>=3.4
  - timezonefinder>=5.2
  - owslib>=0.25
  - richdem>=0.3.4
  - ecCodes
  - pip
  - pip:
      - h5pyd>=0.8
      - astral>=2.2
