name: ssrs_env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib>=3.4
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - pathos>=0.2
  - rasterio>=1.2
  - h5py>=3.4
  - timezonefinder>=5.2
  - owslib>=0.25
  - richdem>=0.3.4
  - pygrib>=2.1.4
  - cartopy>=0.20.3
  - pip
  - pip:
      - elevation>=1.1
      - h5pyd>=0.8
      - astral>=2.2
      - herbie-data
